[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
test = 'test'
script = 'scripts'
cache_path  = 'cache_forge'
solc_version = "0.8.22"
via_ir = true
evm_version = "shanghai"

fs_permissions = [{ access = "read-write", path = "./"}]


[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC}"
base = "${BASE_RPC}"
metis = "${METIS_RPC}"
polygon = "${POLYGON_RPC}"
bsc = "${BSC_RPC}"
optimism = "${OPTIMISM_RPC}"
mantle = "${MANTLE_RPC}"
avalanche = "${AVALANCHE_RPC}"
sei = "${SEI_RPC}"


[etherscan]
arbitrum = { key = "${ARBITRUM_TOKEN}" }
base = { key = "${BASE_TOKEN}"}
metis = { key = "${METIS_TOKEN}"}
polygon = { key =  "${POLYGON_TOKEN}" }
bsc = { key = "${BSC_TOKEN}"}
optimism = { key = "${OPTIMISM_TOKEN}"}
mantle = { key = "${MANTLE_TOKEN}"}
avalanche = { key = "${AVALANCHE_TOKEN}"}
sei = { key = "verifyContract", chain = "1329", url = "https://seitrace.com/pacific-1/api" }